language: python
python:
  - "3.9.7"

install:
  - pip install --upgrade urllib3
  - pip install -r swe_1/requirements.txt
  - pip install coverage coveralls black flake8

before_script:
  - cd swe_1
  - flake8 --max-line-length=88
  - black .

script:
  - coverage run --source=swe_1,polls manage.py test
  - coverage xml
after_success:
  - coveralls --repo_token=$COVERALLS_REPO_TOKEN
branches:
  only:
    - master



deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-west-2"
  app: "django_polls"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-533267125325"
  on:
    branch: master
